
project_id = "rtzitylynowjenfoztum"

# These are the functions that require authentication
[functions]
[functions.check-render-status]
verify_jwt = true

[functions.render-video]
verify_jwt = true

[functions.search-videos]
verify_jwt = true

[functions.generate-audio]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.get-payment-history]
verify_jwt = true

[functions.get-payment-methods]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.increment_video_usage]
verify_jwt = true

# These functions handle payments and don't require authentication as they're called by Paystack
[functions.paystack-webhook]
verify_jwt = false

# Captcha protection is disabled
[auth.captcha]
enabled = false

# Allow specific redirect sites - adding all possible URLs here
[auth]
[auth.redirect_urls]
allowed_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:5173/auth/callback", 
  "https://*.lovable.app/auth/callback", 
  "https://app.smartvideofy.com/auth/callback",
  "https://smartvideofy.com/auth/callback",
  "https://vid-spark-ai-magic.lovable.app/auth/callback"
]
