
project_id = "dijjaulwbvdcnjbqrjdw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Disable JWT verification for the webhook function since it's called by Stripe
[functions.stripe-webhook]
verify_jwt = false

# Create two new functions for video usage tracking
[functions.get_video_usage]
verify_jwt = true

[functions.increment_video_usage]
verify_jwt = true

# Ensure proper JWT verification for other functions
[functions.generate-scenes]
verify_jwt = true

[functions.generate-audio]
verify_jwt = true

[functions.search-videos]
verify_jwt = true

[functions.test-shotstack]
verify_jwt = true

[functions.render-video]
verify_jwt = true

[functions.check-render-status]
verify_jwt = true
