
# This file contains the configuration for your Supabase project

# Project ID for your Supabase project
project_id = "dijjaulwbvdcnjbqrjdw"

[api]
# Port for the API
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["extensions"]
# Maximum rows returns from a view, table, or stored procedure
max_rows = 1000

[db]
# Port for the database
port = 5432
# Database major version. Must be the same as your remote database's version.
major_version = 15

[studio]
# Port for Supabase Studio
port = 54323
# External URL of the API server that Studio should use. Used when the API is behind a reverse proxy or in a staging environment.
# api_url = "https://your-project.supabase.co"

[auth]
# Prevent automatic enabling of Row Level Security on created tables
disable_auto_enable_rls = false

[inbucket]
# Port for the inbucket mock SMTP server
port = 54324

[storage]
# Enable or disable Storage specific features
file_size_limit = "50MiB"

[realtime]
enabled = true

[realtime.tables.public.notifications]
type = "broadcast"
