
project_id = "rtzitylynowjenfoztum"

# These are the functions that require authentication
[functions]
[functions.check-render-status]
verify_jwt = true

[functions.render-video]
verify_jwt = true

[functions.search-videos]
verify_jwt = true

[functions.generate-audio]
verify_jwt = true

# These functions handle payments and don't require authentication as they're called by Stripe
[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-payment-history]
verify_jwt = true

[functions.get-payment-methods]
verify_jwt = true

[functions.increment_video_usage]
verify_jwt = true
