
project_id = "dijjaulwbvdcnjbqrjdw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.generate-audio]
verify_jwt = true

[functions.generate-scenes]
verify_jwt = true 

[functions.check-render-status]
verify_jwt = true

[functions.render-video] 
verify_jwt = true

[functions.search-videos]
verify_jwt = true

[functions.test-shotstack]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
