
project_id = "smartvid"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-audio]
verify_jwt = true

[functions.search-videos]
verify_jwt = true

[functions.generate-scenes]
verify_jwt = true

[functions.render-video]
verify_jwt = true

[functions.check-render-status]
verify_jwt = true
