
project_id = "rtzitylynowjenfoztum"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[[storage.buckets]]
name = "video-assets"
public = true
file_size_limit = "50MiB"
allowed_mime_types = ["audio/mp3", "audio/mpeg", "video/mp4", "image/png", "image/jpeg"]
