// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtzitylynowjenfoztum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eml0eWx5bm93amVuZm96dHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDAyMDUsImV4cCI6MjA2MjI3NjIwNX0.SwmjgSYe5r2nD69YLPu9ZXOBZKYFc9EDTU0SSdc4_mA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);