
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dijjaulwbvdcnjbqrjdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpamphdWx3YnZkY25qYnFyamR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTQ4NDAsImV4cCI6MjA1OTg3MDg0MH0.ZTNdCMBB-5e2MriYCZCWWTdtubxqO9tAnbzikvoF2SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
